---
- name: Create Docker Container
  hosts: pi 
  tasks:
    - name: include variables
      include_vars: vars.yml

    - name: Create Watchtower Container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        volumes:
          - "{{ src_vol }}:{{ dest_vol }}"
        env:
          WATCHTOWER_NOTIFICATIONS: "slack"
          WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ slack_webhook }}"
          WATCHTOWER_SCHEDULE: "0 0 2 * * *"
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_NO_RESTART: "false"
        privileged: "{{ privileged }}"
    
    - name: Create SABnzbd container
      docker_container:
        name: sabnzbd
        image: linuxserver/sabnzbd
        volumes:
          - downloads:/downloads
          - sab_config:/config 
        env:
          PUID: "1001"
          GUID: "1001" 
        ports:
          - "8080:8080"  
        privileged: "{{ privileged }}"

    - name: Create sonarr container
      docker_container:
        name: sonarr
        image: linuxserver/sonarr
        volumes:
          - sonarr_config:/config
          - tv:/tv
          - downloads:/downloads
        env:
          PUID: "1001"
          GUID: "1001"  
        ports:
          - "8989:8989"  
        privileged: "{{ privileged }}"

    - name: Create radarr container
      docker_container:
        name: radarr
        image: linuxserver/radarr
        volumes:
          - radarr_config:/config
          - downloads:/downloads
          - movies:/movies
        env:
          PUID: "1001"
          GUID: "1001"    
        ports:
          - "7878:7878"  
        privileged: "{{ privileged }}"        

    - name: check container status
      command: docker ps
      register: result
    - debug: var=result.stdout
    