---
- name: Create Docker Container
  hosts: pi 
  tasks:
    - name: include variables
      include_vars: vars.yml

    - name: Create Container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        volumes:
          - "{{ src_vol }}:{{ dest_vol }}"
        env:
          WATCHTOWER_NOTIFICATIONS: "slack"
          WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ slack_webhook }}"
          WATCHTOWER_SCHEDULE: "0 0 2 * * *"
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_NO_RESTART: "false"
        privileged: "{{ privileged }}"
    
    - name: Create SABnzbd container
      docker_container:
        name: sabnzbd
        recreate: true
        #restart_policy: unless-stopped
        image: sabnzbd/sabnzbd
        volumes:
          - /downloads:/media
          - /sabdata:/datadir 
        ports:
          - "8080:8080"     
    - name: check container status
      command: docker ps
      register: result
    - debug: var=result.stdout
    